# App Settings
server:
  port: 9094

zuul:
  ws:
    brokerages:
      schedule:
        endPoints: /subscribe
        brokers: /schedule
        destinationPrefixes: /app
        serviceId: schedule-service
  routes:
    booking:
      path: /api/v1/booking/**
      serviceId: booking-service
    schedule:
      path: /api/v1/schedule/**
      serviceId: schedule-service
      customSensitiveHeaders: true
    frontend:
      path: /**
      serviceId: frontend-service


#management:
#  security:
#    enabled: false # TODO: Remove in production!
#
#spring:
#  cloud:
#    gateway:
#      default-filters:
#      - AddResponseHeader=X-Response-Greeting, Hello-World
#
#      # schedule-service
#      routes:
#      - id: schedule-service-subscribe
#        uri: ws://localhost:9091/subscribe
#        order: 9000
#        predicates:
#        - Path=/api/v1/subscribe
#
#      - id: schedule-service-get
#        uri: http://localhost:9091/booking
#        order: 10000
#        predicates:
#        - Path=/api/v1/booking
#        - Method=GET
#
#      # booking-service
#      - id: booking-service
#        uri: http://localhost:9090/booking
#        order: 11000
#        predicates:
#        - Path=/api/v1/booking
#
#      # frontend-service
#      - id: frontend-service
#        uri: http://localhost:9092
#        order: 11000
#        predicates:
#        - Path=/** # All remaining GET paths are directed here.
#        - Method=GET